export { default as Chatbot } from './chatbot.webp';
export { default as Empty } from './empty-books.webp';
export { default as emptyIcon } from './empty-chat.webp';
export { default as ErrorCharacter } from './error-404.webp';
export { default as ExampleBook } from './example-book.webp';
export * from './gradient';
export { default as HomeLogo } from './home-logo.webp';
export { default as Logo } from './logo.webp';
export { default as Onboarding1 } from './onboarding-1.webp';
export { default as Onboarding2 } from './onboarding-2.webp';
export { default as Onboarding3 } from './onboarding-3.webp';
export { default as Summary } from './summary.webp';
